# -*- coding: utf-8 -*-
"""Python_Internal_Assessment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xO8a9U4OXmoFH8PW5Xa65sX9kbHX1Y-4
"""

#1
length=int(input("enter length"))
width=int(input("enter width"))
area=length*width
print(area)

#2
weight=int(input("enter weight in kgs"))
height=int(input("enter height in metres"))
bmi=weight/pow((height),2)
print(bmi*10000)

#3
student={
    "sharez":100,
    "T":90,
    "v":70,
    "A":80
    }

print(student)

#4
age=int(input("Enter Age"))
if(age<18):
  print("Minor")
elif(age>=18 and age<60):
  print("Adult")
else:
  print("Senior")

#5
i=1
for i in range(51):
  if(i%2==0):
    print(i)

#6
pas="123"
val=True
while(val):
  inp=input("Enter Password")
  if(inp==pas):
    print("The Passwords Match")
    val=False
  else:
    continue

#7
def avg(l):
  n=len(l)
  sum=0
  for i in range(n):
    sum=sum+l[i]
  return sum/n
l=[1,2,3,4,5]
print(avg(l))

#8
def vowel(s):
  n=len(s)
  c=0
  for i in range (n):
    if(s[i]=='a' or s[i]=='e' or s[i]=='i' or s[i]=='o' or s[i]=='u'):
      c=c+1
  return c

st=input("Enter String:")
print(vowel(st))

#9)
import datetime
print(datetime.datetime.today())

#10
try:
  def add(a,b):
    return a+b
  inp1=int(input("enter a number"))
  inp2=int(input("enter another number"))
  print(add(inp1,inp2))
except Exception as e:
  print("Enter a Integer to add")

#11
try:
  a=int(input("enter Value:"))
except ValueError:
  print("Enter Integer")

#12
try:
  def div(a,b):
    return a/b
  inp1=int(input("enter a number"))
  inp2=int(input("enter another number"))
  print(div(inp1,inp2))
except ZeroDivisionError :
  print("Denominator Cannot Be Zero")

#13
txtfile=open("/content/3.txt",'w')
txtfile.writelines("Hello,Python!")
txtfile.close()

#14
txtfile=open("/content/3.txt",'r')
print(txtfile.read())
txtfile.close()

#15
txtfile=open("/content/3.txt",'a')
txtfile.writelines("Hi!")
txtfile.close()